/**
 * Reads the src/data/* fixtures and writes supabase/seed.sql — the file that
 * loads every company, glossary term, fundamentals snapshot and news item into
 * the tables from supabase/schema.sql.
 *
 * Run it with:  npx tsx scripts/generate-seed.ts
 * Re-run it whenever the data files change.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { companies } from "../src/data/companies";
import { fundamentals } from "../src/data/fundamentals";
import { glossary } from "../src/data/glossary";
import { news } from "../src/data/news";

/** Wrap a string as a SQL literal, escaping embedded single quotes. */
const s = (value: string) => `'${value.replace(/'/g, "''")}'`;
/** Wrap a value as a SQL jsonb literal. */
const json = (value: unknown) => `${s(JSON.stringify(value))}::jsonb`;
/** Optional text: a SQL literal or NULL. */
const opt = (value: string | undefined) => (value ? s(value) : "null");

const lines: string[] = [
  "-- Generated by scripts/generate-seed.ts — do not edit by hand.",
  "-- Loads the src/data/* fixtures into the schema from supabase/schema.sql.",
  "-- Safe to re-run: it clears the tables first.",
  "",
  "truncate table news, fundamentals, glossary, companies restart identity cascade;",
  "",
];

for (const c of companies) {
  lines.push(
    `insert into companies (symbol, name, sector, description) values ` +
      `(${s(c.symbol)}, ${s(c.name)}, ${s(c.sector)}, ${s(c.description)});`,
  );
}
lines.push("");

for (const g of glossary) {
  lines.push(
    `insert into glossary (id, term, plain_english, analogy) values ` +
      `(${s(g.id)}, ${s(g.term)}, ${s(g.plainEnglish)}, ${opt(g.analogy)});`,
  );
}
lines.push("");

for (const f of fundamentals) {
  lines.push(
    `insert into fundamentals (symbol, as_of, generated, breakdown, metrics) values ` +
      `(${s(f.symbol)}, ${s(f.asOf)}, ${f.generated ? "true" : "false"}, ` +
      `${json(f.breakdown)}, ${json(f.metrics)});`,
  );
}
lines.push("");

for (const n of news) {
  lines.push(
    `insert into news (symbol, headline, summary, source, published_at, url) values ` +
      `(${s(n.symbol)}, ${s(n.headline)}, ${s(n.summary)}, ${s(n.source)}, ` +
      `${s(n.publishedAt)}, ${s(n.url)});`,
  );
}
lines.push("");

mkdirSync("supabase", { recursive: true });
writeFileSync("supabase/seed.sql", lines.join("\n"));

console.log(
  `Wrote supabase/seed.sql — ${companies.length} companies, ` +
    `${glossary.length} glossary terms, ${fundamentals.length} fundamentals, ` +
    `${news.length} news items.`,
);
